Chore: Update to `rdflib>=6`, lower versions are failing the tests
With rdflib-5.x, `testDefaultGraph` produces:

  AttributeError: property 'name' of 'Param' object has no setter